export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const FETCH_PRODUCTS_END = 'FETCH_PRODUCTS_END';

export const SORT_PRODUCTS_SUCCESS = 'SORT_PRODUCTS_SUCCESS';
export const SORT_PRODUCTS_ERROR = 'SORT_PRODUCTS_ERROR';